Testing
YunoHost-Apps/rainloop_ynh pull request #87
Opened 2022-04-01 13:32 UTC by ericgaspar

## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

2022-04-01 13:33 UTC, ericgaspar commented
!testme

2022-04-02 13:19 UTC, yalh76 requested changes
LGTM

2022-04-02 13:19 UTC, yalh76 commented on scripts/upgrade
> -	ynh_app_setting_delete --app=$app --key=$lang
you should keep that, for removal from old versions

2022-04-02 13:42 UTC, ericgaspar commented
!testme

2022-04-03 11:44 UTC, yalh76 requested changes

2022-04-03 11:44 UTC, yalh76 commented on scripts/upgrade
> +fi
won't work because `lang` is not loaded at the LOAD SETTING step, you should let it like it was

2022-04-03 11:49 UTC, ericgaspar commented
!testme

2022-04-04 06:17 UTC, yalh76 approved these changes

2022-04-04 06:21 UTC, merged